package com.myga.learning.backend.backend.dto;

import lombok.Data;

import javax.validation.constraints.Email;
import javax.validation.constraints.NotBlank;
import javax.validation.constraints.Size;

/**
 * Incoming payload for creating or updating a {@code Parent}.
 * The phone (primary key) is generated by the database and is therefore not
 * part of the request body.
 */
@Data
public class ParentRequest {

    @NotBlank(message = "nom is required")
    private String nom;

    @NotBlank(message = "prenom is required")
    private String prenom;

    @NotBlank(message = "email is required")
    @Email(message = "email must be a valid email address")
    private String email;

    /**
     * Optional. When provided on creation, a PARENT login account is
     * provisioned for this parent (email as username). Omit for a
     * domain-only parent record with no login.
     */
    @Size(min = 8, message = "password must be at least 8 characters")
    private String password;
}
